FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         git \
         curl \
         ca-certificates \
         libjpeg-dev \
         libpng-dev && \
     rm -rf /var/lib/apt/lists/*

RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda install conda-build && \
     /opt/conda/bin/conda create -y --name c2019-gpu python=3.6 && \
     /opt/conda/bin/conda clean -ya

ENV PATH /opt/conda/envs/c2019-gpu/bin:$PATH
RUN conda install --name c2019-gpu pytorch torchvision cudatoolkit=9.0 -c pytorch
RUN conda install --name c2019-gpu fire -c conda-forge
RUN conda install --name c2019-gpu fastai -c fastai && /opt/conda/bin/conda clean -ya

RUN mkdir /physionet2019
COPY ./ /physionet2019
WORKDIR /physionet2019
RUN chmod -R a+w /physionet2019
